{% set name = "ipysankeywidget" %}
{% set version = "0.4.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 666a8301c0342a8be03b3791ebde29a140e8085330cb18e829fe2c47dca57856

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python
    - pip
  run:
    - python
    - ipywidgets >=7.0.0

test:
  imports:
    - ipysankeywidget

about:
  home: http://github.com/ricklupton/ipysankeywidget
  license: MIT
  license_family: MIT
  license_file: LICENCE
  summary: IPython / Jupyter Sankey diagram widget

  description: |
    Display Sankey diagrams in Jupyter notebooks, using d3-sankey-diagram.
  doc_url: https://github.com/ricklupton/ipysankeywidget
  dev_url: https://github.com/ricklupton/ipysankeywidget

extra:
  recipe-maintainers:
    - ricklupton
