{% set name = "ipysankeywidget" %}
{% set version = "0.5.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: ed868df0b68ed9c14ad6372a4cec5db99eb43f441b3b4050bc1b454fb817902f

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  build:
    - nodejs >=16
  host:
    - python >=3.7
    - pip
    - jupyter
    - jupyterlab =3
    - jupyter-packaging =0.7
 run:
    - python >=3.7
    - ipywidgets >=7.6.0,<9

test:
  imports:
    - ipysankeywidget
  commands:
    - test -f ${PREFIX}/share/jupyter/nbextensions/jupyter-sankey-widget/extension.js                             # [unix]
    - test -f ${PREFIX}/share/jupyter/nbextensions/jupyter-sankey-widget/index.js                                 # [unix]
    - test -f ${PREFIX}/share/jupyter/labextensions/jupyter-sankey-widget/package.json                            # [unix]
    - if not exist %PREFIX%\\share\\jupyter\\nbextensions\\jupyter-sankey-widget\\extension.js (exit 1)           # [win]
    - if not exist %PREFIX%\\share\\jupyter\\nbextensions\\jupyter-sankey-widget\\index.js (exit 1)               # [win]
    - if not exist %PREFIX%\\share\\jupyter\\labextensions\\jupyter-sankey-widget\\package.json (exit 1)          # [win]

about:
  home: http://github.com/ricklupton/ipysankeywidget
  license: MIT
  license_family: MIT
  license_file: LICENCE
  summary: IPython / Jupyter Sankey diagram widget

  description: |
    Display Sankey diagrams in Jupyter notebooks, using d3-sankey-diagram.
  doc_url: https://github.com/ricklupton/ipysankeywidget
  dev_url: https://github.com/ricklupton/ipysankeywidget

extra:
  recipe-maintainers:
    - ricklupton
