travis:
  secure:
    BINSTAR_TOKEN: DhDam4RZVxwdu3OQ9870mAvffVbl1qUZOGJBW2NFhXCrNctawgyOWpi3zAcXytVLNCM7k1YG11j6NtnqpiTSepqnccsfLD8uSqF3payOEz8IcMii/kfiC0cYn8TyYhV+w+ng+OBKsm6uN8erDLFRD9GYkd7pkUX+TQ7CHLmDRYhQlAvs9sSi9E90U00ViaX6ssoLIKLfR0lPY9nt+itAKSrNTWcKILS5EovvqCgnKQ43p8RB2o1P51dQiKv+yi2wkB5zqo2eSAWA7F82yLSwG4fJPe4TFybstOFs/uN3qGmpSdPogE0XJEZ17jvQtbG0Quwms3hbgCRIC4fFig5TscBmma1Ul6bvEZURJFWsaztI4f7srCuHKznQhNtq3wqih/HIAMZrrUdp24H1gDRPQ6s3Jf3QEDlXJcWEH986npteV0613FOvuE/qmAw43PE2w7sLpNDachRba4jmSfXWGz2zU2vhdGUcXK2aO8bn3Uvw9fEUJJQlSWi2utfLB3uAFEe/NtEcVNf43c3zwLk2hJh5uGUu4I3zxMT/N2OOxCBQiaXtEneND5POkzzbvOaJNjI1zLsefU14vYSybJpzhZidS9VV0oiJ44/bgT0+phvTKeN/kEXWLAdza4qjBS/F0tcvXbXNK1c0OfZ8H01b2PNewa8kbkWo+nYzelooU7g=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
